### ISSUE TITLE
"mvn test" fails with metrics 2.0.0-RC0

### ISSUE THREAD

**Issue by rnewson** [boundary/scalang#5]
Reverting ae851bb0bea091756a3037f6b6ad1d6bddb30d3d fixes 'mvn test'.

Classes like "MetricsRegistry" appear in both the newly introduced metrics-scala dependency and the existing overlock-scala dependency, which probably explains it.

  decode regular terms(scalang.terms.ScalaTermDecoderSpec): java.lang.NoSuchMethodError: com.yammer.metrics.core.MetricsRegistry.newTimer(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;Ljava/util/concurrent/TimeUnit;Ljava/util/concurrent/TimeUnit;)Lcom/yammer/metrics/core/Timer;
  decode full distribution packets(scalang.terms.ScalaTermDecoderSpec): java.lang.NoSuchMethodError: com.yammer.metrics.core.MetricsRegistry.newTimer(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;Ljava/util/concurrent/TimeUnit;Ljava/util/concurrent/TimeUnit;)Lcom/yammer/metrics/core/Timer;

**Comment by rnewson** [comment]
This issue only affects Scalang tests if run with the '0.6.0' from boundary's public maven repo. If I install the '0.6.0' using the latest checkout of the overlock library instead, it passes. Easiest fix is a version bump to overlock, a repo deploy, and a bump to Scalang's dependency of overlock.
